---
# version: 1.0.1
# designed to work with Rocky Linux, not tested on any other Linux distro

- name: Install SNMP
  hosts: localhost
  tasks:
     - name: Install dependencies
       become: true
       ansible.builtin.package:
          name:
             - net-tools
             - net-snmp
             - net-snmp-utils

     # simplest config
     - name: Create SNMPd Config
       become: true
       ansible.builtin.copy:
          dest: /etc/snmp/snmpd.conf
          force: true
          mode: '0600'
          owner: root
          group: root
          content: |
            com2sec readonly  default         public
            group MyROGroup v2c        readonly
            view all    included  .1                               80
            access MyROGroup ""      any       noauth    exact  all    none   none
            syslocation Rack, Room, Building, City, Country [Lat, Lon]
            syscontact Your Name <your@email.address>

     - name: Enable and restart snmpd
       become: true
       ansible.builtin.service:
          name: snmpd
          state: restarted
          enabled: true

     - name: Set Firewall snmp Rules
       become: true
       ansible.builtin.command: firewall-cmd --zone=public --add-service=snmp --permanent

     - name: Enable Firewall Rules
       become: true
       ansible.builtin.command: firewall-cmd --reload

...
