---
# version: 1.0.3

- hosts: localhost
  become_user: root
  tasks:
     - name: Reset SELinux after installs
       become: yes
       command: restorecon -R -v /
       when: (ansible_distribution != "MacOSX") and
             (ansible_os_family != "VMware Photon OS") and
             (ansible_os_family != "Alpine")

