---
# version: 1.0.4

- hosts: localhost
  become_user: root
  tasks:
     - name: Check if ssh reset already completed
       stat:
         path: /etc/ssh/.resetdone
       register: stat_result
       when: ansible_os_family == "RedHat"

     - name: remove IDs
       become: yes
       file:
         path: /etc/machine-id
         state: absent
       when: (not stat_result.stat.exists) and (ansible_os_family == "RedHat")

     - name: find ssh_host files
       become: yes
       find:
         paths: /etc/ssh
         patterns: 'ssh_host_*'
         use_regex: yes
       register: find_result
       when: (not stat_result.stat.exists) and (ansible_os_family == "RedHat")

     - name: remove host keys
       become: yes
       file:
         path: "{{ item.path }}"
         state: absent
       with_items: "{{ find_result.files }}"
       when: (not stat_result.stat.exists) and (ansible_os_family == "RedHat")

     - name: reset SSH Keys/UUID of VM
       become: yes
       command: '{{ item }}'
       loop:
         - "/usr/bin/systemd-machine-id-setup"
       when: (not stat_result.stat.exists) and (ansible_os_family == "RedHat")

     - name: mark ssh reset done
       become: yes
       file:
         path: /etc/ssh/.resetdone
         state: touch
         mode: "0644"
       when: (not stat_result.stat.exists) and (ansible_os_family == "RedHat")
       
     - name: restart sshd
       become: yes
       service:
         name: sshd
         state: restarted
       when: ansible_os_family == "RedHat"

     - name: Reset SELinux after installs
       become: yes
       command: restorecon -R -v /
       when: (ansible_distribution != "MacOSX") and
             (ansible_os_family != "VMware Photon OS") and
             (ansible_os_family != "Alpine")

