---
# version: 1.0.3
#
- name: Install SELinux
  hosts: localhost
  become_user: root
  tasks:
     - name: Install the latest for selinux - RHEL < 8
       become: true
       ansible.builtin.package:
          name:
             - policycoreutils-python
             - setroubleshoot-server
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("8", '<')


     - name: Install the latest for selinux - RHEL = 8
       become: true
       ansible.builtin.package:
          name:
             - python3-policycoreutils
             - setroubleshoot-server
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("8", '=')

     - name: Install the latest for selinux - RHEL > 8
       become: true
       ansible.builtin.package:
          name:
             - policycoreutils-python-utils
             - policycoreutils-newrole
             - policycoreutils-restorecond
             - policycoreutils-sandbox
             - python3-policycoreutils
             - setroubleshoot-server
       when: ansible_os_family == "RedHat" and ansible_distribution_major_version is version("8", '>')

     - name: Install the latest for selinux - Debian
       become: true
       ansible.builtin.package:
          name:
             - policycoreutils
             - selinux-utils
       when: ansible_os_family == "Debian"

...
