---
# version: 1.0.2

- name: Install Open VM Tools
  hosts: localhost
  gather_facts: true
  become_user: root

  tasks:
     - name: Install the latest open-vm-tools for RHEL
       become: true
       ansible.builtin.package:
          name:
             - open-vm-tools
             - cloud-utils-growpart

     # chmod +x /etc/rc.d/rc.local; systemctl enable vmtoolsd
     - name: Get open-vm-tools running
       become: true
       ansible.builtin.file:
          path: /etc/rc.d/rc.local
          mode: u+x,g+x,o+x

     - name: Enable vmtoolsd
       become: true
       ansible.builtin.service:
          name: vmtoolsd
          enabled: true

     - name: Start vmtoolsd
       become: true
       ansible.builtin.service:
          name: vmtoolsd
          state: started

...
