---
# version: 1.0.2
- name: Setup MariaDB
  hosts: localhost
  tasks:
     - name: Install dependencies
       become: true
       ansible.builtin.package:
          name:
             - mariadb
             - mariadb-server
             - mariadb-server-utils
             - "{{ ansible_python.executable | basename }}-PyMySQL"
       when: ansible_distribution != "MacOSX"

     - name: Start mariadb
       become: true
       ansible.builtin.service:
          name: mariadb
          enabled: true
          state: started

     - name: Set my.cnf
       become: true
       ansible.builtin.copy:
          dest: ~/.my.cnf
          mode: "0600"
          content: |
            [client]
            user=root
            password={{ mariadb_pwd }}
       no_log: true

     - name: Remove MySQL test database
       become: true
       community.mysql.mysql_db:
          login_unix_socket: /var/lib/mysql/mysql.sock
          name: test
          state: absent
       no_log: true

     - name: Adjust mariadb bind address
       become: true
       ansible.builtin.lineinfile:
          path: /etc/mysql/mariadb.conf.d/50-server.cnf
          regex: '^bind-address.*\= '
          line: "bind-address = {{ mariadb_bind_address }}"
       when: ansible_os_family == 'Debian'

     - name: Start mariadb
       become: true
       ansible.builtin.service:
          name: mariadb
          enabled: true
          state: restarted
       when: ansible_os_family == 'Debian'

...
