---
# version: 1.0.1

- name: Setup lighttpd
  hosts: localhost
  gather_facts: true
  become_user: root
  tasks:
    - name: Httpd remove
      become: true
      ansible.builtin.package:
        name:
          - httpd
          - httpd-core
          - httpd-tools
          - mod_http2
          - mod_lua
        state: absent

    - name: Lighttpd dependencies
      become: true
      ansible.builtin.package:
        name:
          - lighttpd
          - lighttpd-mod_openssl
          - lighttpd-fastcgi
        state: present

    - name: Stop lighttpd
      become: true
      ansible.builtin.service:
        name: lighttpd
        state: stopped

    - name: Lighttpd TLS
      become: true
      ansible.builtin.copy:
        dest: /etc/lighttpd/conf.d/tls.conf
        mode: '0644'
        owner: root
        group: root
        content: |
          server.modules += ("mod_openssl")
          $SERVER["socket"] == ":443" {{ '{' }}
              ssl.engine = "enable"
              ssl.pemfile = "/etc/pki/tls/certs/{{ ansible_fqdn }}.crt"
              ssl.privkey = "/etc/pki/tls/private/{{ ansible_fqdn }}.key"
          {{ '}' }}

    - name: Add TLS
      become: true
      ansible.builtin.lineinfile:
        path: /etc/lighttpd/lighttpd.conf
        line: 'include "/etc/lighttpd/conf.d/tls.conf"'
        state: present

    - name: Permission private key
      become: true
      ansible.builtin.file:
        path: "/etc/pki/tls/private/{{ ansible_fqdn }}.key"
        owner: lighttpd

    - name: Start lighttpd
      become: true
      ansible.builtin.service:
        name: lighttpd
        state: started
        enabled: true

...
